# Версия конфига
version: 1.0

# Пути к директориям
paths:
  input_dir: /app/input
  output_dir: /app/output
  model_path: /app/model/catboost_model.cbm
  train_data_path: /app/train_data/train.csv
  threshold_path: /app/model/threshold.json
  categorical_features_path: /app/model/categorical_features.json

# Настройки модели
model:
  name: "CatBoostClassifier"
  version: "1.2.8"
  params:
    iterations: 1000
    depth: 6
    learning_rate: 0.1
    loss_function: "Logloss"
    random_state: 42
  preprocessing:
    missing_value_strategy: "median"

# Настройки вывода
output:
  predictions:
    file_prefix: "sample_submission"
    format: "csv"
    include_probabilities: false
  feature_importance:
    file_name: "feature_importance.json"
    top_n: 5
  plots:
    density_plot:
      file_name: "density_plot.png"
      format: "png"
      width: 10
      height: 6
      color: "royalblue"
      title: "Распределение предсказаний"
      dpi: 300

# Безопасность
security:
  file_restrictions:
    allowed_extensions: [".csv"]
    max_size_mb: 50
    required_columns: ["transaction_time", "amount", "gender", "merch", "cat_id"]

# Категориальные признаки
features:
  categorical: []
  numerical: ["amount", "population_city"]
  to_drop:
    - "name_1"
    - "name_2"
    - "street"
    - "post_code"

# Логирование
logging:
  level: "INFO"
  file: "/app/logs/service.log"
  rotation:
    max_size_mb: 10
    backup_count: 3